### PR TITLE
Add a "Filter" box to search through the list of Xbox packages

### PR DESCRIPTION
**Pull request by FlaminSarge**
Also tweak positioning of some UI elements slightly.

This allows people to search through their game list for a particular game.
Filtering only begins at 2+ characters entered, and is removed once <2 characters are in the search box.

Screenshots:
image
image
image

### CODE REVIEW

**Comment by FlaminSarge** [comment]
I spent an inordinate amount of time trying to get DataGridView/BindingSource/BindingListView to work before giving up and going with this impl.

**Comment by Fr33dan** [comment]
This looks good! I'm traveling and away from my PC this week, but I will check it out and merge it next week.

**Comment by FlaminSarge** [comment]
Slightly-related, how viable is it to migrate to a newer .NET runtime so we can just use TextBox.PlaceholderText instead of CueTextBox?

**Comment by Fr33dan** [comment]
I want to stick to a version that's built into Windows so that users don't have to download the runtime separately; enough people I have trouble getting it running without that barrier.  I'm not opposed to upgrading within that criteria but don't know what's the latest version that I could expect users to have by default at this time.

**Comment by FlaminSarge** [comment]
Looks like CueTextBox only shows up in .NET 5 and Win10 by default only ships with 4.6, so we'll forgo that for now.

**Pull request merged**
